In [1]:
import torch

# CL

In [11]:

def create_graph_coloring_hamiltonian(adj_matrix, num_colors):
    """
    Create an Ising Hamiltonian for the graph coloring problem.
    
    Parameters:
    -----------
    adj_matrix : torch.Tensor
        Adjacency matrix of shape (n, n) where n is the number of nodes.
        adj_matrix[i, j] = 1 if nodes i and j are connected, 0 otherwise.
    num_colors : int
        Number of available colors.
        
    Returns:
    --------
    torch.Tensor
        Symmetric tensor representing the Ising Hamiltonian of shape (n*k, n*k).
    """
    num_nodes = adj_matrix.shape[0]
    hamiltonian_size = num_nodes * num_colors
    
    # Initialize the Hamiltonian matrix with zeros
    H = torch.zeros((hamiltonian_size, hamiltonian_size), dtype=torch.float)
    
    # CONSTRAINT 1: Each node must have exactly one color
    for node in range(num_nodes):
        for color1 in range(num_colors):
            # Calculate the index in our flattened representation
            idx1 = node * num_colors + color1
            
            # Encourage having at least one color (negative diagonal term)
            H[idx1, idx1] = -1
            
            # Penalize having multiple colors (positive cross terms)
            for color2 in range(color1+1, num_colors):
                idx2 = node * num_colors + color2
                # Make it energetically unfavorable to have two colors for one node
                H[idx1, idx2] = 2
                H[idx2, idx1] = 2  # Keep it symmetric
    
    # CONSTRAINT 2: Adjacent nodes cannot have the same color
    for node1 in range(num_nodes):
        for node2 in range(node1+1, num_nodes):
            # Check if nodes are adjacent in the graph
            if adj_matrix[node1, node2] > 0:
                for color in range(num_colors):
                    # Find the indices for these node-color combinations
                    idx_node1 = node1 * num_colors + color
                    idx_node2 = node2 * num_colors + color
                    
                    # Penalize adjacent nodes having the same color
                    H[idx_node1, idx_node2] = 2
                    H[idx_node2, idx_node1] = 2  # Keep it symmetric
    
    return H

def create_graph_coloring_hamiltonian_v2(adj_matrix, n_colors, penalty_node=1.0, penalty_edge=1.0):
    n = adj_matrix.shape[0]
    Q = torch.zeros((n * n_colors, n * n_colors), dtype=torch.float32)

    # One-hot color constraint per node
    for i in range(n):
        for c1 in range(n_colors):
            idx1 = i * n_colors + c1
            Q[idx1, idx1] += penalty_node  # X^2 term
            for c2 in range(c1 + 1, n_colors):
                idx2 = i * n_colors + c2
                Q[idx1, idx2] += 2 * penalty_node
                Q[idx2, idx1] += 2 * penalty_node  # ensure symmetry
            Q[idx1, idx1] += -2 * penalty_node  # from -2*X

    # Adjacent nodes with same color
    for i in range(n):
        for j in range(i+1, n):  # upper triangle, symmetric later
            if adj_matrix[i, j] != 0:
                for c in range(n_colors):
                    idx_i = i * n_colors + c
                    idx_j = j * n_colors + c
                    Q[idx_i, idx_j] += penalty_edge
                    Q[idx_j, idx_i] += penalty_edge  # ensure symmetry

    return Q

def decode_coloring(solution_vector, num_nodes, num_colors):
    """
    Convert a solution vector into node color assignments.
    
    Parameters:
    -----------
    solution_vector : torch.Tensor
        Binary vector of shape (n*k,) representing the solution.
    num_nodes : int
        Number of nodes in the graph.
    num_colors : int
        Number of available colors.
        
    Returns:
    --------
    torch.Tensor
        Color assignment for each node.
    """
    # Reshape the flat solution vector into a matrix
    # Each row represents a node, each column represents a color
    node_color_matrix = solution_vector.reshape(num_nodes, num_colors)
    
    # For each node, find which color has a 1 (or the highest value)
    colors = torch.argmax(node_color_matrix, dim=1)
    return colors

def is_valid_coloring(adj_matrix, coloring):
    """
    Check if a coloring assignment is valid (no adjacent nodes have the same color).
    
    Parameters:
    -----------
    adj_matrix : torch.Tensor
        Adjacency matrix of shape (n, n).
    coloring : torch.Tensor
        Color assignments for each node.
        
    Returns:
    --------
    bool
        True if the coloring is valid, False otherwise.
    """
    num_nodes = adj_matrix.shape[0]
    
    # Check all edges
    for node1 in range(num_nodes):
        for node2 in range(node1+1, num_nodes):
            # If nodes are adjacent and have the same color, the coloring is invalid
            if adj_matrix[node1, node2] > 0 and coloring[node1] == coloring[node2]:
                return False
    
    return True


# Create a simple square graph with 4 nodes
num_nodes = 4
num_colors = 2

# Create adjacency matrix for a square/cycle graph
# 0 -- 1
# |    |
# 3 -- 2
adj_matrix = torch.tensor(
    [[0, 1, 0, 1], # 2
    [1, 0, 1, 0],
    [0, 1, 0, 1],
    [1, 0, 1, 0]]
)

# Create the Hamiltonian matrix
H = create_graph_coloring_hamiltonian(adj_matrix, num_colors)
H2 = create_graph_coloring_hamiltonian_v2(adj_matrix, num_colors)

# In practice, you would use a solver to minimize the energy
# For this example, we'll manually create a valid solution

# Create a valid coloring: Nodes 0,2 = color 0, Node 1 = color 1, Node 3 = color 2
solution = torch.zeros(num_nodes * num_colors)
solution[0] = 1              # Node 0 has color 0
solution[num_colors+1] = 1   # Node 1 has color 1
solution[2*num_colors] = 1   # Node 2 has color 0
solution[3*num_colors+1] = 1 # Node 3 has color 2

# Calculate the energy of this solution
energy = solution @ H @ solution
print(f"Energy of valid coloring: {energy.item()}")

# Decode and verify the solution
coloring = decode_coloring(solution, num_nodes, num_colors)
print(f"Node colors: {coloring}")
print(f"Is valid: {is_valid_coloring(adj_matrix, coloring)}")



print(solution)

print(H2)
print(H)
print(adj_matrix)

Energy of valid coloring: -4.0
Node colors: tensor([0, 1, 0, 1])
Is valid: True
tensor([1., 0., 0., 1., 1., 0., 0., 1.])
tensor([[-1.,  2.,  1.,  0.,  0.,  0.,  1.,  0.],
        [ 2., -1.,  0.,  1.,  0.,  0.,  0.,  1.],
        [ 1.,  0., -1.,  2.,  1.,  0.,  0.,  0.],
        [ 0.,  1.,  2., -1.,  0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0., -1.,  2.,  1.,  0.],
        [ 0.,  0.,  0.,  1.,  2., -1.,  0.,  1.],
        [ 1.,  0.,  0.,  0.,  1.,  0., -1.,  2.],
        [ 0.,  1.,  0.,  0.,  0.,  1.,  2., -1.]])
tensor([[-1.,  2.,  2.,  0.,  0.,  0.,  2.,  0.],
        [ 2., -1.,  0.,  2.,  0.,  0.,  0.,  2.],
        [ 2.,  0., -1.,  2.,  2.,  0.,  0.,  0.],
        [ 0.,  2.,  2., -1.,  0.,  2.,  0.,  0.],
        [ 0.,  0.,  2.,  0., -1.,  2.,  2.,  0.],
        [ 0.,  0.,  0.,  2.,  2., -1.,  0.,  2.],
        [ 2.,  0.,  0.,  0.,  2.,  0., -1.,  2.],
        [ 0.,  2.,  0.,  0.,  0.,  2.,  2., -1.]])
tensor([[0, 1, 0, 1],
        [1, 0, 1, 0],
        [0, 1, 0, 1],
        [1,

# CL & CG

In [3]:
# import torch

# def create_graph_coloring_ising_hamiltonian(adj_matrix, k):
#     """
#     Create an Ising Hamiltonian for the graph coloring problem.
    
#     Parameters:
#     -----------
#     adj_matrix : torch.Tensor
#         Adjacency matrix of shape (n, n) where n is the number of nodes.
#         adj_matrix[i, j] = 1 if nodes i and j are adjacent, 0 otherwise.
#     k : int
#         Number of colors.
        
#     Returns:
#     --------
#     torch.Tensor
#         Symmetric tensor representing the Ising Hamiltonian of shape (n*k, n*k).
#     """
#     n = adj_matrix.shape[0]
    
#     # Initialize the Hamiltonian matrix
#     H = torch.zeros((n*k, n*k), dtype=torch.float)
    
#     # Constraint 1: Each node must have exactly one color
#     # Add penalty for a node having multiple colors or no color
#     for i in range(n):
#         for c1 in range(k):
#             idx1 = i * k + c1
            
#             # Diagonal terms for one-hot constraint
#             H[idx1, idx1] = -1
            
#             # Cross terms to penalize multiple colors for the same node
#             for c2 in range(c1+1, k):
#                 idx2 = i * k + c2
#                 H[idx1, idx2] = 2
#                 H[idx2, idx1] = 2
    
#     # Constraint 2: Adjacent nodes cannot have the same color
#     # Add penalty for adjacent nodes having the same color
#     for i in range(n):
#         for j in range(i+1, n):
#             if adj_matrix[i, j] > 0:  # If nodes are adjacent
#                 for c in range(k):
#                     idx_i = i * k + c
#                     idx_j = j * k + c
                    
#                     # Penalty for same color
#                     H[idx_i, idx_j] = 2
#                     H[idx_j, idx_i] = 2
    
#     


# def encode_graph_coloring_ising(adj_matrix, n_colors, penalty_node=1.0, penalty_edge=1.0):
#     n = adj_matrix.shape[0]
#     Q = torch.zeros((n * n_colors, n * n_colors), dtype=torch.float32)

#     # One-hot color constraint per node
#     for i in range(n):
#         for c1 in range(n_colors):
#             idx1 = i * n_colors + c1
#             Q[idx1, idx1] += penalty_node  # X^2 term
#             for c2 in range(c1 + 1, n_colors):
#                 idx2 = i * n_colors + c2
#                 Q[idx1, idx2] += 2 * penalty_node
#                 Q[idx2, idx1] += 2 * penalty_node  # ensure symmetry
#             Q[idx1, idx1] += -2 * penalty_node  # from -2*X

#     # Adjacent nodes with same color
#     for i in range(n):
#         for j in range(i+1, n):  # upper triangle, symmetric later
#             if adj_matrix[i, j] != 0:
#                 for c in range(n_colors):
#                     idx_i = i * n_colors + c
#                     idx_j = j * n_colors + c
#                     Q[idx_i, idx_j] += penalty_edge
#                     Q[idx_j, idx_i] += penalty_edge  # ensure symmetry

#     return Q


# def decode_solution(x, n, k):
#     """
#     Decode the solution from the binary vector.
    
#     Parameters:
#     -----------
#     x : torch.Tensor
#         Binary vector of shape (n*k,) representing the solution.
#     n : int
#         Number of nodes.
#     k : int
#         Number of colors.
        
#     Returns:
#     --------
#     torch.Tensor
#         Coloring assignment of shape (n,) where each element is the color index.
#     """
#     x_reshaped = x.reshape(n, k)
#     colors = torch.argmax(x_reshaped, dim=1)
#     return colors

# def check_solution(adj_matrix, colors):
#     """
#     Check if the coloring is valid.
    
#     Parameters:
#     -----------
#     adj_matrix : torch.Tensor
#         Adjacency matrix of shape (n, n).
#     colors : torch.Tensor
#         Color assignments of shape (n,).
        
#     Returns:
#     --------
#     bool
#         True if the coloring is valid, False otherwise.
#     """
#     n = adj_matrix.shape[0]
    
#     # Check that adjacent nodes have different colors
#     for i in range(n):
#         for j in range(i+1, n):
#             if adj_matrix[i, j] > 0 and colors[i] == colors[j]:
#                 return False
    
#     return True

# # Example usage
# # def example():
# # Create a simple graph with 4 nodes
# n = 4
# k = 2  # 2 colors

# # Create an adjacency matrix for a cycle graph
# adj_matrix = torch.tensor(
#     [[0, 1, 0, 1], # 2
#     [1, 0, 1, 0],
#     [0, 1, 0, 1],
#     [1, 0, 1, 0]]
# )

# # Create the Hamiltonian
# J = create_graph_coloring_ising_hamiltonian(adj_matrix, k)
# print(f"Hamiltonian shape: {J.shape}")

# J2 = encode_graph_coloring_ising(adj_matrix, k)
# print(J2)
# print(J)


# DsB

In [4]:
def run_dsb_simulation(J,  steps=10000, a0=1.0, c0=1.0, dt=0.01):
    """
    Run a (dSB) simulation for solving optimization problems.
    
    Args:
        J: Coupling matrix defining the optimization problem
        steps: Number of simulation steps
        a0: System parameter (constant)
        c0: Coupling strength
        dt: Time step size
    
    Returns:
        binary_solution: The final binary solution (±1 values)
        ising_energy: The Ising energy of the final solution
        x_history: History of position values during simulation
    """
    # Get problem size
    N = J.shape[0]
    
    # Initialize positions and momenta
    x = torch.rand(N, dtype=J.dtype, device=J.device) - 0.5  # Position variables
    y = torch.zeros(N, dtype=J.dtype, device=J.device)       # Momentum variables
    
    # # Initialize history arrays
    # x_history = torch.zeros((steps + 1, N), dtype=J.dtype, device=J.device)
    # x_history[0] = x.clone()
    
    # Define a(t) function - linear increase from 0 to a0
    def a_t_func(t):
        return min(a0 * t / (0.2 * steps * dt), a0)
    
    # Main simulation loop
    for step in range(1, steps + 1):
        t = step * dt
        a_t = a_t_func(t)
        
        # First part of symplectic Euler: update momenta
        # ẏ_i = -[a0 - a(t)]x_i + c0 ∑J_ij*x_j
        y -= dt * ((a0 - a_t) * x - c0 * (torch.matmul(J, torch.sign(x))))
        
        # Second part: update positions
        # ẋ_i = a0 * y_i
        x += dt * a0 * y

        print(x)
        
        # Apply inelastic walls: for any |x_i| > 1
        outside_range = torch.abs(x) > 1.0
        if torch.any(outside_range):
            # Replace with sign (±1)
            x[outside_range] = torch.sign(x[outside_range])
            # Set corresponding momenta to 0
            y[outside_range] = 0.0
        
        # Store current positions
        # x_history[step] = x.clone()
    
    # Get binary solution by taking the sign
    binary_solution = x
    
    # Calculate Ising energy: -0.5 * ∑∑J_ij*s_i*s_j
    ising_energy = -0.5 * torch.sum(torch.matmul(binary_solution, J) * binary_solution)
    
    return binary_solution, ising_energy#, x_history


binary_solution, ising_energy = run_dsb_simulation(H)

binary_solution


tensor([-0.3457, -0.2815, -0.3182,  0.1162, -0.1971, -0.2674, -0.4969,  0.2971])
tensor([-0.3466, -0.2809, -0.3183,  0.1147, -0.1981, -0.2668, -0.4970,  0.2956])
tensor([-0.3480, -0.2799, -0.3185,  0.1126, -0.1995, -0.2658, -0.4971,  0.2934])
tensor([-0.3498, -0.2786, -0.3188,  0.1098, -0.2014, -0.2645, -0.4973,  0.2905])
tensor([-0.3522, -0.2769, -0.3191,  0.1062, -0.2038, -0.2629, -0.4976,  0.2869])
tensor([-0.3550, -0.2750, -0.3195,  0.1019, -0.2067, -0.2609, -0.4979,  0.2825])
tensor([-0.3582, -0.2727, -0.3200,  0.0970, -0.2101, -0.2586, -0.4982,  0.2774])
tensor([-0.3619, -0.2700, -0.3206,  0.0913, -0.2139, -0.2560, -0.4986,  0.2716])
tensor([-0.3661, -0.2671, -0.3212,  0.0849, -0.2182, -0.2531, -0.4991,  0.2650])
tensor([-0.3708, -0.2638, -0.3219,  0.0778, -0.2230, -0.2498, -0.4996,  0.2577])
tensor([-0.3759, -0.2602, -0.3226,  0.0700, -0.2283, -0.2462, -0.5001,  0.2497])
tensor([-0.3815, -0.2563, -0.3234,  0.0614, -0.2340, -0.2423, -0.5007,  0.2410])
tensor([-0.3875, -0.2520, -0

tensor([-1., -1., -1., -1., -1., -1., -1., -1.])