In [ ]:
import numpy as np
from itertools import product

def is_valid_coloring(adj_matrix, coloring):
    """Check if a given coloring is valid (no two adjacent vertices share the same color)."""
    n = len(adj_matrix)
    for i in range(n):
        for j in range(i + 1, n):
            if adj_matrix[i, j] == 1 and coloring[i] == coloring[j]:
                return False
    return True

def find_chromatic_number(adj_matrix):
    """Find the chromatic number by brute force."""
    n = len(adj_matrix)
    for num_colors in range(1, n + 1):  # Try using 1 to n colors
        for coloring in product(range(num_colors), repeat=n):
            if is_valid_coloring(adj_matrix, coloring):
                return num_colors
    return n  # Worst case, n colors are needed

# Define adjacency matrices for various graphs
graph_data = {
    "Triangle Graph (K3)": np.array([[0, 1, 1], # 3
                                      [1, 0, 1],
                                      [1, 1, 0]]),

    "Square Graph (C4)": np.array([[0, 1, 0, 1], # 2
                                    [1, 0, 1, 0],
                                    [0, 1, 0, 1],
                                    [1, 0, 1, 0]]),

    "Star Graph (S3)": np.array([[0, 1, 1, 1], # 2 
                                  [1, 0, 0, 0],
                                  [1, 0, 0, 0],
                                  [1, 0, 0, 0]]),

    "Complete Graph (K5)": np.ones((5, 5)) - np.eye(5), # 5

    "Cycle Graph (C6)": np.array([[0, 1, 0, 0, 0, 1], # 2
                                   [1, 0, 1, 0, 0, 0],
                                   [0, 1, 0, 1, 0, 0],
                                   [0, 0, 1, 0, 1, 0],
                                   [0, 0, 0, 1, 0, 1],
                                   [1, 0, 0, 0, 1, 0]]),

    "Bipartite Graph (K3,3)": np.array([[0, 0, 0, 1, 1, 1], # 2
                                        [0, 0, 0, 1, 1, 1],
                                        [0, 0, 0, 1, 1, 1],
                                        [1, 1, 1, 0, 0, 0],
                                        [1, 1, 1, 0, 0, 0],
                                        [1, 1, 1, 0, 0, 0]])
}

# Compute and print chromatic numbers
for name, matrix in graph_data.items():
    chromatic_num = find_chromatic_number(matrix)
    print(f"{name}:\nAdjacency Matrix:\n{matrix}\nChromatic Number: {chromatic_num}\n{'-'*40}")


Triangle Graph (K3):
Adjacency Matrix:
[[0 1 1]
 [1 0 1]
 [1 1 0]]
Chromatic Number: 3
----------------------------------------
Square Graph (C4):
Adjacency Matrix:
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]
Chromatic Number: 2
----------------------------------------
Star Graph (S3):
Adjacency Matrix:
[[0 1 1 1]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]]
Chromatic Number: 2
----------------------------------------
Complete Graph (K5):
Adjacency Matrix:
[[0. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0.]]
Chromatic Number: 5
----------------------------------------
Cycle Graph (C6):
Adjacency Matrix:
[[0 1 0 0 0 1]
 [1 0 1 0 0 0]
 [0 1 0 1 0 0]
 [0 0 1 0 1 0]
 [0 0 0 1 0 1]
 [1 0 0 0 1 0]]
Chromatic Number: 2
----------------------------------------
Bipartite Graph (K3,3):
Adjacency Matrix:
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [1 1 1 0 0 0]
 [1 1 1 0 0 0]
 [1 1 1 0 0 0]]
Chromatic Number: 2
----------------------------------------
